name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testery:
    runs-on: ubuntu-latest
    env:
      TESTERY_API_KEY: ${{ secrets.TESTERY_API_KEY }}
      TESTERY_ENVIRONMENT_KEY: dev

    steps:
      - uses: actions/checkout@v2

      - name: Upload build to Testery and create a deploy
        run: ./gradlew uploadBuildToTestery notifyTesteryOfDeploy
